### ISSUE TITLE
windows服务器可以使用吗？

### ISSUE THREAD

**Issue by Faputa** [hauntek/python-ngrokd#8]
我用 windows 服务器无法正常使用，应该怎么配置呢？还是说要修改程序？

**Comment by hauntek** [comment]
建议使用支持utf-8编码的编辑器来配置

**Comment by Faputa** [comment]
不管是使用utf-8还是使用utf-8无bom编码都有这个问题：在connt.py的68行也就是对data解码的时候会抛异常：'utf-8' codec can't decode byte 0xfc in position 8: invalid start byte；而在客户端在运行到95行的时候会抛异常：EOF occurred in violation of protocol (_ssl.c:748)

**Comment by Faputa** [comment]
搞定了，是我配置的问题，我分析了一遍程序才配对，如果这个项目有一个比较详尽的文档就好多了
